backend:
  name: git-gateway
  repo: kaselart/kasel-art
  branch: main

media_library:
  name: uploadcare
  config:
    publicKey: c58404de6955163c1bac
  settings:
    defaultOperations: "/resize/200x/"

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "item" # Used in routes, e.g., /admin/collections/blog
    label: "Shop Item" # Used in the UI
    folder: "src/content/items" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {
          label: "Title",
          name: "title",
          widget: "string",
          pattern: ["^.{2,30}$", "30 character maximum"],
        }
      # - {
      #     label: "Slug (replace Title spaces with - ",
      #     name: "slug",
      #     widget: "string",
      #   }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Images",
          name: "images",
          widget: "image",
          media_library: { config: { multiple: true } },
        }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Size", name: "size", widget: "string", required: false }
      - {
          label: "Description",
          name: "body",
          widget: "markdown",
          required: false,
        }
      - { label: "Price", name: "price", widget: "number" }
